name: Test Action

on:
  workflow_dispatch:

jobs:
  test:
    name: "Run Test.md"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          repository: kaiser-chris/pdx-deepl

      - name: Markdown to BBCode
        id: conversion
        uses: kaiser-chris/md2steam-github-action@v1
        with:
          file: 'README.md'

      - name: Results
        run: |
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.conversion.outputs.bbcode }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY