name: Test Action

on:
  workflow_dispatch:

jobs:
  test:
    name: "Run Test.md"
    runs-on: ubuntu-latest
    
    steps:
      - name: Markdown to BBCode
        id: conversion
        uses: ./
        with:
          file: 'Test.md'
      - name: Results
        run: echo "${{ steps.conversion.outputs.bbcode }}" >> $GITHUB_STEP_SUMMARY